'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Locale = 'en' | 'az' | 'ru';

export interface Translations {
  [key: string]: string | string[] | Translations;
}

const translations: Record<Locale, Translations> = {
  en: {
    nav: { home: 'Home', jobs: 'Browse Jobs', companies: 'Companies', pricing: 'Pricing', dashboard: 'Dashboard', signIn: 'Sign In', signUp: 'Get Started', signOut: 'Sign Out', language: 'Language' },
    hero: { badge: '10,000+ active job listings in your area', title: 'Find Your Next Opportunity,', titleAccent: 'Locally', subtitle: 'Find your next opportunity, locally. The fastest way to connect with employers in your city.', searchPlaceholder: 'Job title, keyword, or company', locationPlaceholder: 'City or zip code', search: 'Search', remote: 'Remote', engineering: 'Engineering', marketing: 'Marketing', design: 'Design', sales: 'Sales' },
    stats: { activeJobs: 'Active Jobs', companies: 'Companies', hiredThisMonth: 'Hired This Month', cities: 'Cities' },
    features: { title: 'Everything you need to land your dream job', subtitle: 'Powerful tools designed to make your job search faster and more effective.', localSearch: { title: 'Hyper-Local Search', description: 'Find jobs near you with precise location-based filtering.' }, oneClick: { title: '1-Click Apply', description: 'Apply to jobs instantly with your saved profile.' }, verified: { title: 'Verified Employers', description: 'Every company is verified so you can apply with confidence.' }, tracking: { title: 'Track Applications', description: 'See exactly where you stand with every application.' }, messaging: { title: 'Direct Messaging', description: 'Chat directly with employers and recruiters.' }, aiTips: { title: 'AI Resume Tips', description: 'Get smart suggestions to improve your resume.' } },
    pricing: { title: 'Simple, transparent pricing', subtitle: 'Start free, upgrade when you are ready.', free: { name: 'Free', features: ['Browse all local jobs', 'Create a basic profile', '5 applications per month', 'View company profiles & reviews'] }, premium: { name: 'Premium', period: '/month', badge: 'Most Popular', features: ['Everything in Free', 'Unlimited applications', 'Priority application ranking', 'Advanced job filters', 'Application tracking dashboard', 'AI resume optimization', 'Direct messaging with employers', 'Exclusive premium-only jobs'] }, getStarted: 'Get Started', getStartedFree: 'Get Started Free', currentPlan: 'Current Plan', upgradeNow: 'Upgrade Now', premiumPlan: 'You are on the Premium plan', faq: { title: 'Frequently Asked Questions', cancel: { q: 'Can I cancel anytime?', a: 'Yes! You can cancel your subscription at any time.' }, payment: { q: 'What payment methods do you accept?', a: 'We accept all major credit cards through Stripe.' }, trial: { q: 'Is there a free trial?', a: 'The free plan lets you browse all jobs and apply to up to 5 jobs per month.' }, priority: { q: 'How does priority ranking work?', a: 'Premium applications are highlighted and sorted to the top.' } } },
    cta: { title: 'Ready to find your next opportunity?', subtitle: 'Join thousands of job seekers who have already found their dream jobs through WorkWave.', createAccount: 'Create Free Account', browseJobs: 'Browse Jobs' },
    footer: { description: 'Connecting local talent with local opportunities.', jobSeekers: 'Job Seekers', employers: 'Employers', support: 'Support', browseJobs: 'Browse Jobs', companies: 'Companies', premium: 'Premium', createAccount: 'Create Account', postJob: 'Post a Job', pricing: 'Pricing', companyProfile: 'Company Profile', helpCenter: 'Help Center', privacy: 'Privacy Policy', terms: 'Terms of Service', contact: 'Contact Us', rights: 'All rights reserved.' },
    auth: { login: { title: 'Welcome back', subtitle: 'Sign in to your WorkWave account', email: 'Email', password: 'Password', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'Enter your password', signIn: 'Sign In', signingIn: 'Signing in...', orContinueWith: 'or continue with', continueGoogle: 'Continue with Google', noAccount: "Don't have an account?", signUpFree: 'Sign up free', welcomeBack: 'Welcome back!' }, register: { title: 'Create your account', subtitle: 'Join WorkWave and start your journey', jobSeeker: 'Job Seeker', employer: 'Employer', firstName: 'First Name', lastName: 'Last Name', email: 'Email', password: 'Password', firstNamePlaceholder: 'John', lastNamePlaceholder: 'Doe', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'At least 8 characters', minChars: 'Minimum 8 characters', createAccount: 'Create Account', creatingAccount: 'Creating account...', hasAccount: 'Already have an account?', signIn: 'Sign in', terms: 'By creating an account, you agree to our', termsOfService: 'Terms of Service', and: 'and', privacyPolicy: 'Privacy Policy', accountCreated: 'Account created! Welcome to WorkWave' }, error: { title: 'Authentication Error', configuration: 'There is a problem with the server configuration.', accessDenied: 'You do not have permission to access this resource.', verification: 'The verification link may have expired.', default: 'An error occurred during authentication.', tryAgain: 'Try Again', goHome: 'Go Home' } },
    jobs: { searchPlaceholder: 'Search jobs, skills, companies...', cityPlaceholder: 'City or zip code', filters: 'Filters', jobType: 'Job Type', workModel: 'Work Model', experienceLevel: 'Experience Level', industry: 'Industry', allIndustries: 'All Industries', searching: 'Searching...', jobsFound: 'jobs found', noJobs: 'No jobs found', noJobsDesc: 'Try adjusting your search or filters', sort: { newest: 'Newest First', salaryHigh: 'Highest Salary', salaryLow: 'Lowest Salary', oldest: 'Oldest First' }, badges: { featured: 'Featured', premium: 'Premium', urgent: 'Urgent' }, previous: 'Previous', next: 'Next', page: 'Page', of: 'of', more: 'more' },
    jobDetail: { backToJobs: 'Back to jobs', applyNow: 'Apply Now', applied: 'Applied', saved: 'Saved', save: 'Save', share: 'Share', aboutRole: 'About this role', requirements: 'Requirements', responsibilities: 'Responsibilities', skills: 'Skills', jobDetails: 'Job Details', salary: 'Salary', jobType: 'Job Type', workModel: 'Work Model', experience: 'Experience', industry: 'Industry', posted: 'Posted', benefits: 'Benefits', about: 'About', viewCompany: 'View Company Profile', applyModal: { title: 'Apply to', at: 'at', coverLetter: 'Cover Letter (optional)', coverLetterPlaceholder: 'Tell the employer why you are a great fit...', submit: 'Submit Application', submitting: 'Submitting...', cancel: 'Cancel' }, notSpecified: 'Not specified', perYear: '/ year', toasts: { applied: 'Application submitted successfully!', failed: 'Failed to apply', saved: 'Job saved!', unsaved: 'Job unsaved', saveFailed: 'Failed to save job' }, reviews: 'Reviews', pros: 'Pros', cons: 'Cons', openPositions: 'Open Positions', noPositions: 'No open positions at the moment', companyNotFound: 'Company not found', verified: 'Verified', employees: 'employees', badges: { featured: 'Featured', premium: 'Premium Only', urgent: 'Urgent' } },
    companies: { title: 'Companies', hiring: 'companies hiring on WorkWave', searchPlaceholder: 'Search companies...', noCompanies: 'No companies found', noCompaniesDesc: 'Try a different search term', openJobs: 'open jobs' },
    dashboard: { welcome: 'Welcome back', welcomeName: 'Welcome back,', subtitle: "Here's what's happening with your job search", upgradePremium: 'Upgrade to Premium', postJob: 'Post a Job', freePlan: 'Free Plan', runningLow: 'Running Low', remainingApps: 'applications remaining this month', unlimitedApps: 'Unlimited applications', upgradeDesc: 'Upgrade to Premium for unlimited applications, priority ranking, and more.', upgradePrice: 'Upgrade - $9.99/mo', stats: { applications: 'Applications', remaining: 'Remaining', profileViews: 'Profile Views', plan: 'Plan', thisMonth: 'this month', premiumPlan: 'Premium plan', applicationsLeft: 'applications left', totalViews: 'total views', active: 'active', upgradeAvailable: 'upgrade available' }, recentApps: 'Recent Applications', viewAll: 'View all', noApps: 'No applications yet', noAppsDesc: 'Start applying to jobs to track your progress here.', browseJobs: 'Browse Jobs', quickActions: 'Quick Actions', editProfile: 'Edit Profile', savedJobs: 'Saved Jobs', applications: 'Applications', recommended: 'Recommended', unlimited: 'Unlimited', premium: 'Premium', free: 'Free' },
    applications: { title: 'My Applications', total: 'total applications', browseJobs: 'Browse Jobs', all: 'All', noApps: 'No applications found', noAppsFiltered: 'No applications with this status', noAppsDesc: 'Start applying to jobs to see them here', priority: 'Priority', applied: 'Applied', withdraw: 'Withdraw', interview: 'Interview scheduled:', confirmWithdraw: 'Are you sure you want to withdraw this application?', previous: 'Previous', next: 'Next', employerTitle: 'Applications to Your Jobs', employerTotal: 'total applications received', noEmployerApps: 'No applications yet. Post a job to start receiving applications.', postJob: 'Post a Job', viewDetails: 'View Details', experience: 'exp', coverLetter: 'Cover Letter', statusUpdated: 'Status updated successfully', updateFailed: 'Failed to update application', withdrawn: 'Application withdrawn', withdrawFailed: 'Failed to withdraw application', pending: 'Pending', reviewed: 'Reviewed', shortlisted: 'Shortlisted', interviews: 'Interviews', backToApplications: 'Back to Applications', applicantInfo: 'Applicant Information', email: 'Email', phone: 'Phone', location: 'Location', years: 'years', experienceLevel: 'Experience Level', resume: 'Resume', downloadResume: 'Download Resume', skills: 'Skills', about: 'About', jobDetails: 'Job Details', jobTitle: 'Job Title', company: 'Company', appliedOn: 'Applied On', salaryExpectation: 'Salary Expectation', availableFrom: 'Available From', manageApplication: 'Manage Application', status: 'Status', interviewDate: 'Interview Date', employerNotes: 'Employer Notes', notesPlaceholder: 'Add private notes about this applicant...', updateApplication: 'Update Application', updating: 'Updating...', timeline: 'Timeline', interviewScheduled: 'Interview Scheduled' },
    profile: { title: 'Edit Profile', subtitle: 'Keep your profile up to date to attract employers', saveChanges: 'Save Changes', saving: 'Saving...', basicInfo: 'Basic Information', firstName: 'First Name', lastName: 'Last Name', headline: 'Headline', headlinePlaceholder: 'e.g. Senior Software Engineer with 5+ years experience', phone: 'Phone', phonePlaceholder: '+1 (555) 000-0000', city: 'City', cityPlaceholder: 'San Francisco', state: 'State', statePlaceholder: 'CA', about: 'About', bioPlaceholder: 'Tell employers about yourself...', experience: 'Experience', yearsExp: 'Years of Experience', expLevel: 'Experience Level', salaryExp: 'Salary Expectation (annual)', salaryPlaceholder: 'e.g. 80000', openToWork: 'Open to work', skills: 'Skills', skillPlaceholder: 'Type a skill and press Enter', add: 'Add', popularSkills: 'Popular skills:', links: 'Links', linkedin: 'LinkedIn URL', linkedinPlaceholder: 'https://linkedin.com/in/yourname', portfolio: 'Portfolio URL', portfolioPlaceholder: 'https://yourportfolio.com', github: 'GitHub URL', githubPlaceholder: 'https://github.com/yourname', resume: 'Resume', uploadResume: 'Upload your resume', resumeFormats: 'PDF, DOC, or DOCX up to 5MB', saveAll: 'Save All Changes' },
    messages: { title: 'Messages', premiumFeature: 'Premium Feature', premiumDesc: 'Direct messaging is available for Premium members', upgradePremium: 'Upgrade to Premium', searchPlaceholder: 'Search conversations...', noConversations: 'No conversations yet', conversation: 'Conversation', back: 'Back', typePlaceholder: 'Type a message...', send: 'Send', selectConversation: 'Select a conversation to start messaging', toasts: { failed: 'Failed to send', sendFailed: 'Failed to send message' } },
    saved: { title: 'Saved Jobs', savedCount: 'saved jobs', noSaved: 'No saved jobs', noSavedDesc: 'Save jobs to review them later', browseJobs: 'Browse Jobs', removed: 'Job removed from saved', removeFailed: 'Failed to remove' },
    postJob: { createCompany: 'Create Company Profile', createCompanyDesc: 'You need a company profile before posting jobs', companyName: 'Company Name *', description: 'Description', industry: 'Industry', selectIndustry: 'Select', website: 'Website', city: 'City', state: 'State', createCompanyBtn: 'Create Company', title: 'Post a Job', subtitle: 'Fill in the details to create a new job listing', jobDetails: 'Job Details', jobTitle: 'Job Title *', jobTitlePlaceholder: 'e.g. Senior Software Engineer', jobDesc: 'Description *', jobDescPlaceholder: 'Describe the role, team, and what makes this opportunity special...', jobType: 'Job Type', workModel: 'Work Model', expLevel: 'Experience Level', locationSalary: 'Location & Salary', minSalary: 'Min Salary (annual)', maxSalary: 'Max Salary (annual)', salaryPlaceholder: 'e.g. 50000', requirements: 'Requirements', reqPlaceholder: 'e.g. 3+ years of React experience', addReq: '+ Add Requirement', responsibilities: 'Responsibilities', respPlaceholder: 'e.g. Design and implement new features', addResp: '+ Add Responsibility', benefits: 'Benefits', benefitPlaceholder: 'e.g. Health insurance', addBenefit: '+ Add Benefit', requiredSkills: 'Required Skills', skillPlaceholder: 'Type a skill and press Enter', add: 'Add', postJob: 'Post Job', posting: 'Posting...', companyCreated: 'Company created!', jobPosted: 'Job posted!' },
    admin: { dashboard: 'Admin Dashboard', subtitle: 'Platform overview and management', manageUsers: 'Manage Users', manageJobs: 'Manage Jobs', stats: { totalUsers: 'Total Users', activeJobs: 'Active Jobs', applications: 'Applications', revenue: 'Revenue', premiumUsers: 'Premium Users', companies: 'Companies', thisMonth: 'this month', total: 'total', conversion: 'conversion', verified: 'verified' }, userGrowth: 'User Growth (6 months)', jobsByType: 'Jobs by Type', appsByStatus: 'Applications by Status', jobs: { title: 'Manage Jobs', searchPlaceholder: 'Search jobs or companies...', job: 'Job', company: 'Company', applications: 'Applications', views: 'Views', status: 'Status', actions: 'Actions', active: 'Active', inactive: 'Inactive', deactivate: 'Deactivate', activate: 'Activate', unfeature: 'Unfeature', feature: 'Feature', noJobs: 'No jobs found' }, users: { title: 'Manage Users', searchPlaceholder: 'Search by email or name...', allRoles: 'All Roles', jobSeekers: 'Job Seekers', employers: 'Employers', recruiters: 'Recruiters', admins: 'Admins', user: 'User', role: 'Role', plan: 'Plan', applications: 'Applications', joined: 'Joined', actions: 'Actions', deactivate: 'Deactivate', activate: 'Activate', noUsers: 'No users found' }, previous: 'Previous', next: 'Next' },
    common: { loading: 'Loading...', somethingWrong: 'Something went wrong' },
  },
  az: {
    nav: { home: 'Ana Səhifə', jobs: 'Vakansiyalar', companies: 'Şirkətlər', pricing: 'Qiymətlər', dashboard: 'İdarə Paneli', signIn: 'Daxil Ol', signUp: 'Başla', signOut: 'Çıxış', language: 'Dil' },
    hero: { badge: 'Bölgənizdə 10,000+ aktiv vakansiya', title: 'Növbəti Fürsətinizi Tapın,', titleAccent: 'Yerli Olaraq', subtitle: 'Növbəti fürsətinizi, yerli olaraq tapın.', searchPlaceholder: 'Vəzifə, açar söz və ya şirkət', locationPlaceholder: 'Şəhər və ya poçt kodu', search: 'Axtar', remote: 'Məsafədən', engineering: 'Mühəndislik', marketing: 'Marketinq', design: 'Dizayn', sales: 'Satış' },
    stats: { activeJobs: 'Aktiv Vakansiyalar', companies: 'Şirkətlər', hiredThisMonth: 'Bu Ay İşə Götürülənlər', cities: 'Şəhərlər' },
    features: { title: 'Xəyal işinizi tapmaq üçün lazım olan hər şey', subtitle: 'İş axtarışınızı daha sürətli etmək üçün hazırlanmış güclü alətlər.', localSearch: { title: 'Hiper-Yerli Axtarış', description: 'Dəqiq filtrasiya ilə yaxınlınızdakı işləri tapın.' }, oneClick: { title: '1-Klik Müraciət', description: 'Saxlanmış profilinizlə dərhal müraciət edin.' }, verified: { title: 'Təsdiqlənmiş İşəgötürənlər', description: 'Hər şirkət təsdiqlənib.' }, tracking: { title: 'Müraciətləri İzləyin', description: 'Hər müraciətinizi izləyin.' }, messaging: { title: 'Birbaşa Mesajlaşma', description: 'İşəgötürənlərlə birbaşa danışın.' }, aiTips: { title: 'CV Məsləhətləri', description: 'CV-nizi yaxşılaşdırmaq üçün tövsiyələr.' } },
    pricing: { title: 'Sadə, şəffaf qiymətlər', subtitle: 'Pulsuz başlayın, hazır olanda yüksəldin.', free: { name: 'Pulsuz', features: ['Bütün yerli işlərə baxın', 'Əsas profil yaradın', 'Aya 5 müraciət', 'Şirkət profillərinə baxın'] }, premium: { name: 'Premium', period: '/ay', badge: 'Ən Populyar', features: ['Pulsuz paktda olan hər şey', 'Limitsiz müraciətlər', 'Prioritet sıralama', 'Təkmil filtrlər', 'İzləmə paneli', 'CV optimallaşdırması', 'Birbaşa mesajlaşma', 'Xüsusi işlər'] }, getStarted: 'Başla', getStartedFree: 'Pulsuz Başla', currentPlan: 'Cari Plan', upgradeNow: 'İndi Yüksəlt', premiumPlan: 'Premium planındasınız', faq: { title: 'Tez-tez Verilən Suallar', cancel: { q: 'İstənilən vaxt ləğv edə bilərəmmi?', a: 'Bəli!' }, payment: { q: 'Hansı ödəniş üsullarını qəbul edirsiniz?', a: 'Kredit kartları.' }, trial: { q: 'Pulsuz sınaq varmı?', a: 'Bəli, pulsuz plan mövcuddur.' }, priority: { q: 'Prioritet sıralama necə işləyir?', a: 'Müraciətlər yuxarıda göstərilir.' } } },
    cta: { title: 'Növbəti fürsətinizi tapmağa hazırsınız?', subtitle: 'WorkWave vasitəsilə iş tapan minlərlə insana qoşulun.', createAccount: 'Pulsuz Hesab Yaradın', browseJobs: 'Vakansiyaları Gör' },
    footer: { description: 'Yerli istedadları yerli fürsətlərlə birləşdiririk.', jobSeekers: 'İş Axtaranlar', employers: 'İşəgötürənlər', support: 'Dəstək', browseJobs: 'Vakansiyaları Gör', companies: 'Şirkətlər', premium: 'Premium', createAccount: 'Hesab Yaradın', postJob: 'İş Yerləşdir', pricing: 'Qiymətlər', companyProfile: 'Şirkət Profili', helpCenter: 'Kömək Mərkəzi', privacy: 'Məxfilik Siyasəti', terms: 'Xidmət Şərtləri', contact: 'Bizimlə Əlaqə', rights: 'Bütün hüquqlar qorunur.' },
    auth: { login: { title: 'Xoş gəlmisiniz', subtitle: 'WorkWave hesabınıza daxil olun', email: 'E-poçt', password: 'Şifrə', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'Şifrənizi daxil edin', signIn: 'Daxil Ol', signingIn: 'Daxil olunur...', orContinueWith: 'və ya davam edin', continueGoogle: 'Google ilə davam edin', noAccount: 'Hesabınız yoxdur?', signUpFree: 'Pulsuz qeydiyyat', welcomeBack: 'Xoş gəldiniz!' }, register: { title: 'Hesabınızı yaradın', subtitle: 'WorkWave-a qoşulun', jobSeeker: 'İş Axtaran', employer: 'İşəgötürən', firstName: 'Ad', lastName: 'Soyad', email: 'E-poçt', password: 'Şifrə', firstNamePlaceholder: 'Ad', lastNamePlaceholder: 'Soyad', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'Ən azı 8 simvol', minChars: 'Minimum 8 simvol', createAccount: 'Hesab Yaradın', creatingAccount: 'Yaradılır...', hasAccount: 'Artıq hesabınız var?', signIn: 'Daxil olun', terms: 'Hesab yaradaraq razılaşırsınız', termsOfService: 'Xidmət Şərtləri', and: 'və', privacyPolicy: 'Məxfilik Siyasəti', accountCreated: 'Hesab yaradıldı! WorkWave-a xoş gəldiniz' }, error: { title: 'Autentifikasiya Xətası', configuration: 'Server konfiqurasiyasında problem var.', accessDenied: 'Giriş icazəniz yoxdur.', verification: 'Doğrulama linki bitmiş ola bilər.', default: 'Xəta baş verdi.', tryAgain: 'Yenidən Cəhd Edin', goHome: 'Ana Səhifə' } },
    jobs: { searchPlaceholder: 'İş, bacarıq, şirkət axtar...', cityPlaceholder: 'Şəhər', filters: 'Filtrlər', jobType: 'İş Növü', workModel: 'İş Modeli', experienceLevel: 'Təcrübə', industry: 'Sənaye', allIndustries: 'Hamısı', searching: 'Axtarılır...', jobsFound: 'iş tapıldı', noJobs: 'İş tapılmadı', noJobsDesc: 'Filtrləri dəyişdirin', sort: { newest: 'Ən Yeni', salaryHigh: 'Yüksək Maaş', salaryLow: 'Aşağı Maaş', oldest: 'Ən Köhnə' }, badges: { featured: 'Seçilmiş', premium: 'Premium', urgent: 'Təcili' }, previous: 'Əvvəlki', next: 'Növbəti', page: 'Səhifə', of: '/', more: 'daha çox' },
    jobDetail: { backToJobs: 'İşlərə qayıt', applyNow: 'İndi Müraciət Et', applied: 'Müraciət Edilib', saved: 'Saxlanıldı', save: 'Saxla', share: 'Paylaş', aboutRole: 'Rol haqqında', requirements: 'Tələblər', responsibilities: 'Məsuliyyətlər', skills: 'Bacarıqlar', jobDetails: 'Təfərrüatlar', salary: 'Maaş', jobType: 'Növ', workModel: 'Model', experience: 'Təcrübə', industry: 'Sənaye', posted: 'Yerləşdirilib', benefits: 'Faydalar', about: 'Haqqında', viewCompany: 'Şirkət Profili', applyModal: { title: 'Müraciət:', at: '-', coverLetter: 'Məktub', coverLetterPlaceholder: 'Səbəb...', submit: 'Göndər', submitting: 'Göndərilir...', cancel: 'Ləğv' }, notSpecified: 'Göstərilməyib', perYear: '/ il', toasts: { applied: 'Uğurla göndərildi!', failed: 'Uğursuz oldu', saved: 'Saxlanıldı!', unsaved: 'Silindi', saveFailed: 'Xəta' }, reviews: 'Rəylər', pros: 'Müsbət', cons: 'Mənfi', openPositions: 'Açıq Vəzifələr', noPositions: 'Vəzifə yoxdur', companyNotFound: 'Tapılmadı', verified: 'Təsdiqlənmiş', employees: 'işçi', badges: { featured: 'Seçilmiş', premium: 'Premium', urgent: 'Təcili' } },
    companies: { title: 'Şirkətlər', hiring: 'WorkWave-da işə götürən', searchPlaceholder: 'Şirkət axtar...', noCompanies: 'Tapılmadı', noCompaniesDesc: 'Yenidən cəhd edin', openJobs: 'açıq iş' },
    dashboard: { welcome: 'Xoş gəldiniz', welcomeName: 'Xoş gəldiniz,', subtitle: 'İş axtarışınız', upgradePremium: 'Premium-a Yüksəlt', postJob: 'İş Yerləşdir', freePlan: 'Pulsuz Plan', runningLow: 'Azalır', remainingApps: 'qalan müraciət', unlimitedApps: 'Limitsiz', upgradeDesc: 'Limitsiz müraciətlər üçün.', upgradePrice: 'Yüksəlt - $9.99/ay', stats: { applications: 'Müraciətlər', remaining: 'Qalan', profileViews: 'Baxışlar', plan: 'Plan', thisMonth: 'bu ay', premiumPlan: 'Premium', applicationsLeft: 'qalan', totalViews: 'ümumi', active: 'aktiv', upgradeAvailable: 'mövcuddur' }, recentApps: 'Son Müraciətlər', viewAll: 'Hamısı', noApps: 'Yoxdur', noAppsDesc: 'Müraciət edin.', browseJobs: 'Vakansiyalar', quickActions: 'Əməliyyatlar', editProfile: 'Redaktə', savedJobs: 'Saxlanılan', applications: 'Müraciətlər', recommended: 'Tövsiyə', unlimited: 'Limitsiz', premium: 'Premium', free: 'Pulsuz' },
    applications: { title: 'Müraciətlərim', total: 'ümumi', browseJobs: 'Vakansiyalar', all: 'Hamısı', noApps: 'Tapılmadı', noAppsFiltered: 'Yoxdur', noAppsDesc: 'Müraciət edin', priority: 'Prioritet', applied: 'Edilib', withdraw: 'Geri Çək', interview: 'Müsahibə:', confirmWithdraw: 'Əminsiniz?', previous: 'Əvvəlki', next: 'Növbəti', employerTitle: 'Şirkətinizə Müraciətlər', employerTotal: 'ümumi müraciət', noEmployerApps: 'Hələ müraciət yoxdur. İş yerləşdirin.', postJob: 'İş Yerləşdir', viewDetails: 'Ətraflı Bax', experience: 'il təcrübə', coverLetter: 'Məktub', statusUpdated: 'Status yeniləndi', updateFailed: 'Yenilənmədi', withdrawn: 'Geri çəkildi', withdrawFailed: 'Geri çəkilmədi', pending: 'Gözləyir', reviewed: 'Baxılıb', shortlisted: 'Seçilib', interviews: 'Müsahibələr', backToApplications: 'Geri', applicantInfo: 'Məlumat', email: 'E-poçt', phone: 'Telefon', location: 'Məkan', years: 'il', experienceLevel: 'Səviyyə', resume: 'CV', downloadResume: 'Yüklə', skills: 'Bacarıqlar', about: 'Haqqında', jobDetails: 'Təfərrüatlar', jobTitle: 'Vəzifə', company: 'Şirkət', appliedOn: 'Tarix', salaryExpectation: 'Maaş', availableFrom: 'Başlaya bilər', manageApplication: 'İdarə Et', status: 'Status', interviewDate: 'Müsahibə Tarixi', employerNotes: 'Qeydlər', notesPlaceholder: 'Qeyd əlavə edin...', updateApplication: 'Yenilə', updating: 'Yenilənir...', timeline: 'Tarixçə', interviewScheduled: 'Müsahibə Təyin Edildi' },
    profile: { title: 'Profili Redaktə Et', subtitle: 'Yeniləyin', saveChanges: 'Saxla', saving: 'Saxlanılır...', basicInfo: 'Əsas', firstName: 'Ad', lastName: 'Soyad', headline: 'Başlıq', headlinePlaceholder: '...', phone: 'Telefon', phonePlaceholder: '...', city: 'Şəhər', cityPlaceholder: 'Bakı', state: 'Bölgə', statePlaceholder: 'Bakı', about: 'Haqqında', bioPlaceholder: '...', experience: 'Təcrübə', yearsExp: 'İl', expLevel: 'Səviyyə', salaryExp: 'Maaş', salaryPlaceholder: '...', openToWork: 'Açıqdır', skills: 'Bacarıqlar', skillPlaceholder: '...', add: 'Əlavə et', popularSkills: 'Populyar:', links: 'Keçidlər', linkedin: 'LinkedIn', linkedinPlaceholder: '...', portfolio: 'Portfolio', portfolioPlaceholder: '...', github: 'GitHub', githubPlaceholder: '...', resume: 'CV', uploadResume: 'Yüklə', resumeFormats: 'PDF, DOC', saveAll: 'Hamısını Saxla' },
    messages: { title: 'Mesajlar', premiumFeature: 'Premium', premiumDesc: 'Yalnız Premium', upgradePremium: 'Yüksəlt', searchPlaceholder: 'Axtar...', noConversations: 'Yoxdur', conversation: 'Söhbət', back: 'Geri', typePlaceholder: 'Yazın...', send: 'Göndər', selectConversation: 'Seçin', toasts: { failed: 'Xəta', sendFailed: 'Göndərilmədi' } },
    saved: { title: 'Saxlanılan', savedCount: 'saxlanılan', noSaved: 'Yoxdur', noSavedDesc: 'Saxlayın', browseJobs: 'Vakansiyalar', removed: 'Silindi', removeFailed: 'Xəta' },
    postJob: { createCompany: 'Şirkət Yaradın', createCompanyDesc: 'Əvvəlcə şirkət yaradın', companyName: 'Ad *', description: 'Təsvir', industry: 'Sənaye', selectIndustry: 'Seçin', website: 'Sayt', city: 'Şəhər', state: 'Bölgə', createCompanyBtn: 'Yarat', title: 'İş Yerləşdir', subtitle: 'Məlumatları doldurun', jobDetails: 'Təfərrüat', jobTitle: 'Vəzifə *', jobTitlePlaceholder: '...', jobDesc: 'Təsvir *', jobDescPlaceholder: '...', jobType: 'Növ', workModel: 'Model', expLevel: 'Səviyyə', locationSalary: 'Məkan & Maaş', minSalary: 'Min Maaş', maxSalary: 'Max Maaş', salaryPlaceholder: '...', requirements: 'Tələblər', reqPlaceholder: '...', addReq: '+ Tələb', responsibilities: 'Məsuliyyətlər', respPlaceholder: '...', addResp: '+ Məsuliyyət', benefits: 'Faydalar', benefitPlaceholder: '...', addBenefit: '+ Fayda', requiredSkills: 'Bacarıqlar', skillPlaceholder: '...', add: 'Əlavə et', postJob: 'Yerləşdir', posting: 'Yerləşdirilir...', companyCreated: 'Yaradıldı!', jobPosted: 'Yerləşdirildi!' },
    admin: { dashboard: 'Admin', subtitle: 'İdarəetmə', manageUsers: 'İstifadəçilər', manageJobs: 'İşlər', stats: { totalUsers: 'İstifadəçilər', activeJobs: 'İşlər', applications: 'Müraciətlər', revenue: 'Gəlir', premiumUsers: 'Premium', companies: 'Şirkətlər', thisMonth: 'bu ay', total: 'ümumi', conversion: 'konversiya', verified: 'təsdiq' }, userGrowth: 'Artım', jobsByType: 'Növə Görə', appsByStatus: 'Statusa Görə', jobs: { title: 'İşlər', searchPlaceholder: 'Axtar...', job: 'İş', company: 'Şirkət', applications: 'Müraciətlər', views: 'Baxışlar', status: 'Status', actions: 'Əməliyyat', active: 'Aktiv', inactive: 'Qeyri-aktiv', deactivate: 'Deaktiv', activate: 'Aktiv', unfeature: 'Çıxar', feature: 'Seç', noJobs: 'Yoxdur' }, users: { title: 'İstifadəçilər', searchPlaceholder: 'Axtar...', allRoles: 'Hamısı', jobSeekers: 'Axtaranlar', employers: 'İşəgötürənlər', recruiters: 'Recruiterlər', admins: 'Adminlər', user: 'İstifadəçi', role: 'Rolu', plan: 'Plan', applications: 'Müraciətlər', joined: 'Qoşulub', actions: 'Əməliyyat', deactivate: 'Deaktiv', activate: 'Aktiv', noUsers: 'Yoxdur' }, previous: 'Əvvəlki', next: 'Növbəti' },
    common: { loading: 'Yüklənir...', somethingWrong: 'Xəta baş verdi' },
  },
  ru: {
    nav: { home: 'Главная', jobs: 'Вакансии', companies: 'Компании', pricing: 'Цены', dashboard: 'Панель', signIn: 'Войти', signUp: 'Начать', signOut: 'Выйти', language: 'Язык' },
    hero: { badge: '10,000+ вакансий в вашем регионе', title: 'Найдите Свою Возможность,', titleAccent: 'Локально', subtitle: 'Найдите работу локально.', searchPlaceholder: 'Должность или компания', locationPlaceholder: 'Город', search: 'Поиск', remote: 'Удалённо', engineering: 'Инженерия', marketing: 'Маркетинг', design: 'Дизайн', sales: 'Продажи' },
    stats: { activeJobs: 'Вакансии', companies: 'Компании', hiredThisMonth: 'Нанятых', cities: 'Города' },
    features: { title: 'Всё для поиска работы', subtitle: 'Инструменты для быстрого поиска.', localSearch: { title: 'Локальный Поиск', description: 'Находите работы рядом.' }, oneClick: { title: 'Заявка в 1 Клик', description: 'Подавайте мгновенно.' }, verified: { title: 'Проверенные', description: 'Компании проверены.' }, tracking: { title: 'Отслеживание', description: 'Следите за статусом.' }, messaging: { title: 'Сообщения', description: 'Общайтесь напрямую.' }, aiTips: { title: 'Советы по Резюме', description: 'Улучшайте резюме.' } },
    pricing: { title: 'Простые цены', subtitle: 'Начните бесплатно.', free: { name: 'Бесплатно', features: ['Просмотр вакансий', 'Профиль', '5 заявок в месяц', 'Профили компаний'] }, premium: { name: 'Премиум', period: '/месяц', badge: 'Популярный', features: ['Всё из бесплатного', 'Безлимитные заявки', 'Приоритет', 'Фильтры', 'Панель', 'Резюме', 'Сообщения', 'Эксклюзив'] }, getStarted: 'Начать', getStartedFree: 'Бесплатно', currentPlan: 'Текущий', upgradeNow: 'Обновить', premiumPlan: 'Вы на Премиум', faq: { title: 'Вопросы', cancel: { q: 'Можно отменить?', a: 'Да.' }, payment: { q: 'Способы оплаты?', a: 'Карты.' }, trial: { q: 'Пробный период?', a: 'Есть бесплатный план.' }, priority: { q: 'Как работает приоритет?', a: 'Заявки выше.' } } },
    cta: { title: 'Готовы найти работу?', subtitle: 'Присоединяйтесь к WorkWave.', createAccount: 'Создать Аккаунт', browseJobs: 'Вакансии' },
    footer: { description: 'Соединяем таланты с возможностями.', jobSeekers: 'Соискателям', employers: 'Работодателям', support: 'Поддержка', browseJobs: 'Вакансии', companies: 'Компании', premium: 'Премиум', createAccount: 'Аккаунт', postJob: 'Разместить', pricing: 'Цены', companyProfile: 'Профиль', helpCenter: 'Помощь', privacy: 'Конфиденциальность', terms: 'Условия', contact: 'Контакты', rights: 'Все права защищены.' },
    auth: { login: { title: 'С возвращением', subtitle: 'Войдите в WorkWave', email: 'Email', password: 'Пароль', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'Введите пароль', signIn: 'Войти', signingIn: 'Вход...', orContinueWith: 'или', continueGoogle: 'Google', noAccount: 'Нет аккаунта?', signUpFree: 'Регистрация', welcomeBack: 'С возвращением!' }, register: { title: 'Создайте аккаунт', subtitle: 'Присоединяйтесь к WorkWave', jobSeeker: 'Соискатель', employer: 'Работодатель', firstName: 'Имя', lastName: 'Фамилия', email: 'Email', password: 'Пароль', firstNamePlaceholder: 'Иван', lastNamePlaceholder: 'Иванов', emailPlaceholder: 'you@example.com', passwordPlaceholder: 'Минимум 8 символов', minChars: 'Минимум 8 символов', createAccount: 'Создать', creatingAccount: 'Создание...', hasAccount: 'Есть аккаунт?', signIn: 'Войти', terms: 'Соглашаясь, вы принимаете', termsOfService: 'Условия', and: 'и', privacyPolicy: 'Политику', accountCreated: 'Аккаунт создан! Добро пожаловать в WorkWave' }, error: { title: 'Ошибка', configuration: 'Проблема с сервером.', accessDenied: 'Нет доступа.', verification: 'Ссылка истекла.', default: 'Ошибка.', tryAgain: 'Повторить', goHome: 'На Главную' } },
    jobs: { searchPlaceholder: 'Поиск вакансий...', cityPlaceholder: 'Город', filters: 'Фильтры', jobType: 'Тип', workModel: 'Формат', experienceLevel: 'Опыт', industry: 'Отрасль', allIndustries: 'Все', searching: 'Поиск...', jobsFound: 'найдено', noJobs: 'Не найдено', noJobsDesc: 'Измените фильтры', sort: { newest: 'Новые', salaryHigh: 'Высокая ЗП', salaryLow: 'Низкая ЗП', oldest: 'Старые' }, badges: { featured: 'Рекомендуемая', premium: 'Премиум', urgent: 'Срочно' }, previous: 'Назад', next: 'Далее', page: 'Страница', of: 'из', more: 'ещё' },
    jobDetail: { backToJobs: 'Назад', applyNow: 'Откликнуться', applied: 'Откликнулись', saved: 'Сохранено', save: 'Сохранить', share: 'Поделиться', aboutRole: 'О позиции', requirements: 'Требования', responsibilities: 'Обязанности', skills: 'Навыки', jobDetails: 'Детали', salary: 'Зарплата', jobType: 'Тип', workModel: 'Формат', experience: 'Опыт', industry: 'Отрасль', posted: 'Опубликовано', benefits: 'Преимущества', about: 'О', viewCompany: 'Профиль', applyModal: { title: 'Отклик на', at: 'в', coverLetter: 'Письмо', coverLetterPlaceholder: 'Расскажите...', submit: 'Отправить', submitting: 'Отправка...', cancel: 'Отмена' }, notSpecified: 'Не указано', perYear: '/ год', toasts: { applied: 'Отправлено!', failed: 'Ошибка', saved: 'Сохранено!', unsaved: 'Удалено', saveFailed: 'Ошибка' }, reviews: 'Отзывы', pros: 'Плюсы', cons: 'Минусы', openPositions: 'Позиции', noPositions: 'Нет позиций', companyNotFound: 'Не найдена', verified: 'Проверена', employees: 'сотрудников', badges: { featured: 'Рекомендуемая', premium: 'Премиум', urgent: 'Срочно' } },
    companies: { title: 'Компании', hiring: 'нанимают на WorkWave', searchPlaceholder: 'Поиск...', noCompanies: 'Не найдены', noCompaniesDesc: 'Попробуйте другой запрос', openJobs: 'вакансий' },
    dashboard: { welcome: 'С возвращением', welcomeName: 'С возвращением,', subtitle: 'Ваш поиск работы', upgradePremium: 'Обновить', postJob: 'Разместить', freePlan: 'Бесплатный', runningLow: 'Заканчивается', remainingApps: 'заявок осталось', unlimitedApps: 'Безлимитно', upgradeDesc: 'Обновитесь для безлимита.', upgradePrice: 'Обновить - $9.99/мес', stats: { applications: 'Заявки', remaining: 'Осталось', profileViews: 'Просмотры', plan: 'План', thisMonth: 'в этом месяце', premiumPlan: 'Премиум', applicationsLeft: 'заявок', totalViews: 'просмотров', active: 'активен', upgradeAvailable: 'доступно' }, recentApps: 'Заявки', viewAll: 'Все', noApps: 'Нет', noAppsDesc: 'Начните откликаться.', browseJobs: 'Вакансии', quickActions: 'Действия', editProfile: 'Профиль', savedJobs: 'Сохранённые', applications: 'Заявки', recommended: 'Рекомендовано', unlimited: 'Безлимитно', premium: 'Премиум', free: 'Бесплатно' },
    applications: { title: 'Мои Заявки', total: 'всего', browseJobs: 'Вакансии', all: 'Все', noApps: 'Не найдены', noAppsFiltered: 'Нет', noAppsDesc: 'Откликайтесь', priority: 'Приоритет', applied: 'Подана', withdraw: 'Отозвать', interview: 'Собеседование:', confirmWithdraw: 'Отозвать?', previous: 'Назад', next: 'Далее', employerTitle: 'Заявки на Ваши Вакансии', employerTotal: 'всего заявок', noEmployerApps: 'Заявок пока нет. Разместите вакансию.', postJob: 'Разместить Вакансию', viewDetails: 'Подробнее', experience: 'опыт', coverLetter: 'Сопроводительное', statusUpdated: 'Статус обновлён', updateFailed: 'Ошибка обновления', withdrawn: 'Отозвано', withdrawFailed: 'Ошибка отзыва', pending: 'Ожидает', reviewed: 'Просмотрено', shortlisted: 'В шорт-листе', interviews: 'Собеседования', backToApplications: 'Назад', applicantInfo: 'Информация о Кандидате', email: 'Email', phone: 'Телефон', location: 'Местоположение', years: 'лет', experienceLevel: 'Уровень Опыта', resume: 'Резюме', downloadResume: 'Скачать', skills: 'Навыки', about: 'О Себе', jobDetails: 'Детали Вакансии', jobTitle: 'Должность', company: 'Компания', appliedOn: 'Дата Заявки', salaryExpectation: 'Ожидаемая ЗП', availableFrom: 'Доступен С', manageApplication: 'Управление', status: 'Статус', interviewDate: 'Дата Собеседования', employerNotes: 'Заметки Работодателя', notesPlaceholder: 'Добавьте заметки о кандидате...', updateApplication: 'Обновить', updating: 'Обновление...', timeline: 'История', interviewScheduled: 'Собеседование Назначено' },
    profile: { title: 'Редактировать', subtitle: 'Обновляйте профиль', saveChanges: 'Сохранить', saving: 'Сохранение...', basicInfo: 'Основное', firstName: 'Имя', lastName: 'Фамилия', headline: 'Заголовок', headlinePlaceholder: '...', phone: 'Телефон', phonePlaceholder: '...', city: 'Город', cityPlaceholder: 'Москва', state: 'Регион', statePlaceholder: 'МО', about: 'О себе', bioPlaceholder: '...', experience: 'Опыт', yearsExp: 'Лет', expLevel: 'Уровень', salaryExp: 'Зарплата', salaryPlaceholder: '...', openToWork: 'Открыт', skills: 'Навыки', skillPlaceholder: '...', add: 'Добавить', popularSkills: 'Популярные:', links: 'Ссылки', linkedin: 'LinkedIn', linkedinPlaceholder: '...', portfolio: 'Портфолио', portfolioPlaceholder: '...', github: 'GitHub', githubPlaceholder: '...', resume: 'Резюме', uploadResume: 'Загрузить', resumeFormats: 'PDF, DOC', saveAll: 'Сохранить Всё' },
    messages: { title: 'Сообщения', premiumFeature: 'Премиум', premiumDesc: 'Только для Премиум', upgradePremium: 'Обновить', searchPlaceholder: 'Поиск...', noConversations: 'Нет', conversation: 'Беседа', back: 'Назад', typePlaceholder: 'Напишите...', send: 'Отправить', selectConversation: 'Выберите', toasts: { failed: 'Ошибка', sendFailed: 'Не отправлено' } },
    saved: { title: 'Сохранённые', savedCount: 'сохранённых', noSaved: 'Нет', noSavedDesc: 'Сохраняйте', browseJobs: 'Вакансии', removed: 'Удалено', removeFailed: 'Ошибка' },
    postJob: { createCompany: 'Создать Компанию', createCompanyDesc: 'Сначала создайте компанию', companyName: 'Название *', description: 'Описание', industry: 'Отрасль', selectIndustry: 'Выберите', website: 'Сайт', city: 'Город', state: 'Регион', createCompanyBtn: 'Создать', title: 'Разместить', subtitle: 'Заполните данные', jobDetails: 'Детали', jobTitle: 'Должность *', jobTitlePlaceholder: '...', jobDesc: 'Описание *', jobDescPlaceholder: '...', jobType: 'Тип', workModel: 'Формат', expLevel: 'Уровень', locationSalary: 'Место и ЗП', minSalary: 'Мин ЗП', maxSalary: 'Макс ЗП', salaryPlaceholder: '...', requirements: 'Требования', reqPlaceholder: '...', addReq: '+ Требование', responsibilities: 'Обязанности', respPlaceholder: '...', addResp: '+ Обязанность', benefits: 'Преимущества', benefitPlaceholder: '...', addBenefit: '+ Преимущество', requiredSkills: 'Навыки', skillPlaceholder: '...', add: 'Добавить', postJob: 'Разместить', posting: 'Публикация...', companyCreated: 'Создана!', jobPosted: 'Опубликована!' },
    admin: { dashboard: 'Админ', subtitle: 'Управление', manageUsers: 'Пользователи', manageJobs: 'Вакансии', stats: { totalUsers: 'Пользователи', activeJobs: 'Вакансии', applications: 'Заявки', revenue: 'Доход', premiumUsers: 'Премиум', companies: 'Компании', thisMonth: 'в этом месяце', total: 'всего', conversion: 'конверсия', verified: 'проверено' }, userGrowth: 'Рост', jobsByType: 'По Типу', appsByStatus: 'По Статусу', jobs: { title: 'Вакансии', searchPlaceholder: 'Поиск...', job: 'Вакансия', company: 'Компания', applications: 'Заявки', views: 'Просмотры', status: 'Статус', actions: 'Действия', active: 'Активна', inactive: 'Неактивна', deactivate: 'Деактивировать', activate: 'Активировать', unfeature: 'Убрать', feature: 'Рекомендовать', noJobs: 'Не найдены' }, users: { title: 'Пользователи', searchPlaceholder: 'Поиск...', allRoles: 'Все', jobSeekers: 'Соискатели', employers: 'Работодатели', recruiters: 'Рекрутеры', admins: 'Админы', user: 'Пользователь', role: 'Роль', plan: 'План', applications: 'Заявки', joined: 'Регистрация', actions: 'Действия', deactivate: 'Деактивировать', activate: 'Активировать', noUsers: 'Не найдены' }, previous: 'Назад', next: 'Далее' },
    common: { loading: 'Загрузка...', somethingWrong: 'Что-то пошло не так' },
  },
};

interface I18nContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string | string[];
}

const I18nContext = createContext<I18nContextType | undefined>(undefined);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('en');

  useEffect(() => {
    const saved = localStorage.getItem('workwave-locale') as Locale;
    if (saved && ['en', 'az', 'ru'].includes(saved)) {
      setLocaleState(saved);
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('workwave-locale', newLocale);
    document.documentElement.lang = newLocale;
  };

  const t = (key: string): string | string[] => {
    const keys = key.split('.');
    let value: any = translations[locale];
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    return value;
  };

  return (
    <I18nContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) {
    throw new Error('useI18n must be used within an I18nProvider');
  }
  return context;
}

export const LOCALE_NAMES: Record<Locale, string> = {
  en: 'English',
  az: 'Azərbaycan',
  ru: 'Русский',
};

export const LOCALE_FLAGS: Record<Locale, string> = {
  en: '🇺',
  az: '🇿',
  ru: '🇷',
};
